import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filme:
        </h1>

      <Link href='/busca'> Ir para a Busca</Link>



      </main>

      <footer className={styles.footer}>
        <p>Luci Lua</p>
      </footer>
    </div>
  )
}

//static generation

export async function getStaticProps(context){

  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`)
  const json = await res.json()


  return {
    props: {
      info: json
    } 
  }
}
