import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filme: {info.title}
        </h1>

        <h1>Sinopse</h1>
        <p>
            {info.overview}
        </p>

        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="400"/>

      <Link href='/busca'> Ir para a Busca</Link>



      </main>

      <footer className={styles.footer}>
        <p>Luci Lua</p>
      </footer>
    </div>
  )
}


export async function getServerSideProps(context){

  const res = await fetch(`https://themoviesdb.vercel.app/api/movie/${context.params.id}`)
  const json = await res.json()


  return {
    props: {
      info: json.info
    } 
  }
}
