import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Busca({list}) {

    const [searchText, setSearchText]  = useState('')
    const [movieList, setMovieList] = useState([]);

    const handleSearch = async () => {
        if(searchText !== ''){
            const result = await fetch(`https://themoviesdb.vercel.app/api/search?q=${searchText}`)
            const json = await result.json();

            setMovieList(json.list)
        }
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Busca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Busca
        </h1>

     <input type='text' value={searchText} onChange={e => setSearchText(e.target.value)}/>
    Termo de busca: {searchText}

    <button onClick={handleSearch}>Buscar</button>

    <hr />

    <ul>
        {movieList.map(item => {
          <li>
            <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150" />
                <span>{item.title}</span>
            </a>
          </li>
        })}
    </ul>

      </main>

      <footer className={styles.footer}>
        <p>Luci Lua</p>
      </footer>
    </div>
  )
}

// client side rendering
